### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by netesheng** [edp963/davinci-docker#1]
run docker-compose up -d error
![捕获1](https://user-images.githubusercontent.com/9253891/56469964-f589aa00-6472-11e9-885a-21f7e6af459c.PNG)
![捕获2](https://user-images.githubusercontent.com/9253891/56469962-ee629c00-6472-11e9-9162-f00c69eea9ff.PNG)
![捕获3](https://user-images.githubusercontent.com/9253891/56469967-fae6f480-6472-11e9-83f2-34be6c0e5f1d.PNG)

**Comment by cabbage89** [comment]
https://docs.docker.com/compose/compose-file/    

update your docker compose version
