### ISSUE TITLE
本地编译成功后，启动后，无法访问页面

### ISSUE THREAD

**Issue by chaozhangpower** [edp963/davinci-docker#27]

**Comment by chaozhangpower** [comment]
能完善本地编译方式嘛？

**Comment by chaozhangpower** [comment]
![Uploading image.png…]()

**Comment by chaozhangpower** [comment]
![image](https://user-images.githubusercontent.com/21254276/94126845-b68f2d80-fe8a-11ea-86e9-655411c9c2f7.png)

**Comment by chaozhangpower** [comment]
Resolved

**Comment by Phukety** [comment]
> Resolved

您好，请问您是怎样解决的这个问题的呢，我也遇到了，感谢
