### ISSUE TITLE
求助。。镜像构建成功，但是docker启动的时候报错

### ISSUE THREAD

**Issue by CharlesTHN** [edp963/davinci-docker#28]
启动命令：
docker run -p 58081:8080 -e SPRING_DATASOURCE_URL="jdbc:mysql://***:3306/davinci0.3?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true" \
-e SPRING_DATASOURCE_USERNAME="root" -e SPRING_DATASOURCE_PASSWORD="root" \
-e SPRING_MAIL_HOST="smtp.qq.com"  -e SPRING_MAIL_PORT="465" -e SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE="true" \
-e SPRING_MAIL_USERNAME="277391273@qq.com"  -e SPRING_MAIL_PASSWORD="***" \
-e SPRING_MAIL_NICKNAME="davinci_sys" \
edp963/davinci:v0.3.0-beta.9

报错信息：
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./bin/start-server.sh\": stat ./bin/start-server.sh: no such file or directory": unknown.
ERRO[0000] error waiting for container: context canceled

**Comment by cabbage89** [comment]
windows上需要把 sh文件转为 linux文件换行符,再构建
